use_frameworks!
platform :ios, '12.0'

target 'DPAPI_Example' do
  pod 'DPAPI', :path => '../'
  
#  pod 'Alamofire'
#  pod 'RxSwift'

  target 'DPAPI_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
